<a href="https://colab.research.google.com/github/Shamil2007/Python-Libraries/blob/main/pandas_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

What is Pandas?
Pandas is an open-source Python library providing high-performance, easy-to-use data structures and data analysis tools. It's built on top of NumPy and is particularly suited for working with structured (tabular, multidimensional, potentially heterogeneous) data.

Key features:

- Handling missing data

- Size mutability (columns can be inserted/deleted)

- Automatic and explicit data alignment

- Powerful group by functionality

- Time series functionality

In [1]:
import pandas as pd

#Creating a Series

In [2]:
#From a list
numbers = pd.Series([1, 3, 5, 7, 9])
numbers

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [3]:
#With custom index
numbers = pd.Series([1, 3, 5, 7, 9], index = ['a', 'b', 'c', 'd', 'e'])
numbers

a    1
b    3
c    5
d    7
e    9
dtype: int64

In [4]:
#From a dictionary
data = {'a': 1, 'b': 3, 'c': 5, 'd': 7, 'e': 9}
numbers = pd.Series(data)
numbers

a    1
b    3
c    5
d    7
e    9
dtype: int64

#Key Series Attributes

In [5]:
numbers.values

array([1, 3, 5, 7, 9])

In [6]:
numbers.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [7]:
numbers.dtype

dtype('int64')

In [8]:
numbers.size

5

#Basic Operations

Arthmetic operations

In [9]:
numbers + 10

a    11
b    13
c    15
d    17
e    19
dtype: int64

In [10]:
numbers * 2

a     2
b     6
c    10
d    14
e    18
dtype: int64

In [11]:
numbers / 2

a    0.5
b    1.5
c    2.5
d    3.5
e    4.5
dtype: float64

Boolean filtering

In [12]:
numbers[numbers > 5]

d    7
e    9
dtype: int64

In [13]:
numbers[numbers / 2 < 5]

a    1
b    3
c    5
d    7
e    9
dtype: int64

Statistical operations

In [14]:
numbers.mean()

np.float64(5.0)

In [15]:
numbers.std()

3.1622776601683795

In [16]:
numbers.sum()

np.int64(25)

In [17]:
numbers[numbers.mean() > numbers]

a    1
b    3
dtype: int64

#Practice Exercises:

- Create a Series from a list of temperatures in Celsius: [22.5, 25.3, 19.7, 21.8, 23.1]. Set the index as ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'].

- Convert these temperatures to Fahrenheit (F = C * 9/5 + 32) using Series operations.

- Select only the temperatures above 23°C.

In [18]:
temps = [22.5, 25.3, 19.7, 21.8, 23.1]
days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']

temps_celsius = pd.Series(temps, index=days)
temps_celsius

Mon    22.5
Tue    25.3
Wed    19.7
Thu    21.8
Fri    23.1
dtype: float64

In [19]:
temps_fahrenheit = temps_celsius * 9 / 5 + 32
temps_fahrenheit

Mon    72.50
Tue    77.54
Wed    67.46
Thu    71.24
Fri    73.58
dtype: float64

In [20]:
temps_celsius[temps_celsius > 23]

Tue    25.3
Fri    23.1
dtype: float64

#Creating DataFrames

In [21]:
# From a dictionary of lists
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['NY', 'Paris', 'London', 'Tokyo']
}

In [22]:
df = pd.DataFrame(data)
df

      Name  Age    City
0    Alice   25      NY
1      Bob   30   Paris
2  Charlie   35  London
3    David   40   Tokyo

In [23]:
# From a list of dictionaries
data_list = [
    {'Name': 'Alice', 'Age': 25, 'City': 'NY'},
    {'Name': 'Bob', 'Age': 30, 'City': 'Paris'},
    # ... more records
]

df_list = pd.DataFrame(data)
df_list

      Name  Age    City
0    Alice   25      NY
1      Bob   30   Paris
2  Charlie   35  London
3    David   40   Tokyo

In [24]:
df = pd.DataFrame(data, index=['a', 'b', 'c', 'd'])
df

      Name  Age    City
a    Alice   25      NY
b      Bob   30   Paris
c  Charlie   35  London
d    David   40   Tokyo

#DataFrame Attributes and Methods

In [25]:
df.shape # (rows, columns)

(4, 3)

In [26]:
df.columns # column names

Index(['Name', 'Age', 'City'], dtype='object')

In [27]:
df.index # row index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [28]:
df.dtypes # data types per column

Name    object
Age      int64
City    object
dtype: object

In [29]:
n = 3
df.head(n) # first n rows

      Name  Age    City
a    Alice   25      NY
b      Bob   30   Paris
c  Charlie   35  London

In [30]:
n = 3
df.tail(n) # last n rows

      Name  Age    City
b      Bob   30   Paris
c  Charlie   35  London
d    David   40   Tokyo

In [31]:
df.info() # concise summary

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, a to d
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [32]:
df.describe() # statistical summary

             Age
count   4.000000
mean   32.500000
std     6.454972
min    25.000000
25%    28.750000
50%    32.500000
75%    36.250000
max    40.000000

#Selecting Data

In [33]:
# Single column (returns Series)
df['Name']

a      Alice
b        Bob
c    Charlie
d      David
Name: Name, dtype: object

In [34]:
# Multiple columns (returns DataFrame)
df[['Name', 'Age']]

      Name  Age
a    Alice   25
b      Bob   30
c  Charlie   35
d    David   40

In [35]:
#Rows by label
df.loc['a']

Name    Alice
Age        25
City       NY
Name: a, dtype: object

In [36]:
# Rows by position
df.iloc[0]

Name    Alice
Age        25
City       NY
Name: a, dtype: object

In [37]:
# Boolean indexing
df[df['Age'] > 30]

      Name  Age    City
c  Charlie   35  London
d    David   40   Tokyo

#Adding / Modifying Data

In [38]:
# Adding new column
df['Salary'] = [70_000, 80_000, 90_000, 100_000]
df

      Name  Age    City  Salary
a    Alice   25      NY   70000
b      Bob   30   Paris   80000
c  Charlie   35  London   90000
d    David   40   Tokyo  100000

In [39]:
# Modify Column
df['Age'] = df['Age'] + 1
df

      Name  Age    City  Salary
a    Alice   26      NY   70000
b      Bob   31   Paris   80000
c  Charlie   36  London   90000
d    David   41   Tokyo  100000

In [40]:
# Delete column
del df['City']
df

      Name  Age  Salary
a    Alice   26   70000
b      Bob   31   80000
c  Charlie   36   90000
d    David   41  100000

The line - df.drop('City', axis=1, inplace=True) - does the same thing as the previous code. The axis=1 part means that the column named "City" will be deleted. If it was axis=0, it would mean that a row would be deleted. The inplace=True part means that the changes will be applied directly to the original dataframe, so there’s no need to assign it to a new variable.

#Practice Exercises:

- Create a DataFrame for a student database with columns: ID, Name, Major, GPA.

- Select only the students with GPA > 3.5.

- Add a new column "Graduated" with boolean values.

In [41]:
IDs = [2025001, 2025002, 2025003, 2025004]
Names = ['Alice', 'Bob', 'Charlie', 'Diana']
Majors = ['Computer Science', 'Mathematics', 'Physics', 'Biology']
GPAs = [2.8, 4.5, 3.9, 3.7] # out of 5

student_db = pd.DataFrame({'ID': IDs,
                          'Name': Names,
                          'Major': Majors,
                          'GPA': GPAs})
student_db

        ID     Name             Major  GPA
0  2025001    Alice  Computer Science  2.8
1  2025002      Bob       Mathematics  4.5
2  2025003  Charlie           Physics  3.9
3  2025004    Diana           Biology  3.7

In [42]:
student_db[student_db['GPA'] > 3.5]

        ID     Name        Major  GPA
1  2025002      Bob  Mathematics  4.5
2  2025003  Charlie      Physics  3.9
3  2025004    Diana      Biology  3.7

In [43]:
student_db['Graduated'] = [False, True, True, False]
student_db

        ID     Name             Major  GPA  Graduated
0  2025001    Alice  Computer Science  2.8      False
1  2025002      Bob       Mathematics  4.5       True
2  2025003  Charlie           Physics  3.9       True
3  2025004    Diana           Biology  3.7      False

#Data Cleaning and Preparation

In [44]:
import numpy as np

data = {
    'customer_id': [101, np.nan, 103, 104, 105, 101, 106, 107, 108, 104],
    'name': ['Alice Smith', 'Bob Johnson', 'Charlie Brown', None, 'Eve Wilson',
             'alice smith', 'Frank White', 'Grace Lee', 'Henry Ford', 'David King'],
    'age': [25, 32, np.nan, 45, 28, 25, 72, 31, 150, 40],
    'email': [
        'alice@example.com',
        'bob@example.com',
         None,
         None,
        'eve@example.com',
        'alice@example.com',
        'frank@example.com',
        None,
        'henry@example.com',
        'david@example.com'
    ],
    'join_date': [
        None,
        '2021-11-03',
        '2023-02-20',
        '2022-06-18',
        '2023-01-01',
        '2022-01-15',
        '2020-05-12',
        '2022-08-22',
         None,
        '2022-06-18'
    ],
    'purchase_amount': [120.50, 80.25, 200.00, np.nan, 55.75, np.nan, 300.00, 90.00, 25.50, 180.00],
    'loyalty_member': [None, 'No', 'yes', 'no', 'YES', 'Yes', 'no', None, 'yes', 'No'],
    'last_purchase': [
        '2023-04-10',
        '2023-03-15',
        '2023-04-01',
        None,
        '2023-04-05',
        '2023-04-10',
        '2023-02-28',
        '2023-03-22',
        '1996-01-15',
        None
    ]
}

df = pd.DataFrame(data)
print("Original Dataset:")
print(df)

Original Dataset:
   customer_id           name    age              email   join_date  \
0        101.0    Alice Smith   25.0  alice@example.com        None
1          NaN    Bob Johnson   32.0    bob@example.com  2021-11-03
2        103.0  Charlie Brown    NaN               None  2023-02-20
3        104.0           None   45.0               None  2022-06-18
4        105.0     Eve Wilson   28.0    eve@example.com  2023-01-01
5        101.0    alice smith   25.0  alice@example.com  2022-01-15
6        106.0    Frank White   72.0  frank@example.com  2020-05-12
7        107.0      Grace Lee   31.0               None  2022-08-22
8        108.0     Henry Ford  150.0  henry@example.com        None
9        104.0     David King   40.0  david@example.com  2022-06-18

   purchase_amount loyalty_member last_purchase
0           120.50           None    2023-04-10
1            80.25             No    2023-03-15
2           200.00            yes    2023-04-01
3              NaN             no          None
4            55.75            YES    2023-04-05
5              NaN            Yes    2023-04-10
6           300.00             no    2023-02-28
7            90.00           None    2023-03-22
8            25.50            yes    1996-01-15
9           180.00             No          None

# Handling Missing Data

In [45]:
# Detect missing values
df.isna()

,customer_id,name,age,email,join_date,purchase_amount,loyalty_member,last_purchase
0,False,False,False,False,True,False,True,False
1,True,False,False,False,False,False,False,False
2,False,False,True,True,False,False,False,False
3,False,True,False,True,False,True,False,True
4,False,False,False,False,False,False,False,False
5,False,False,False,False,False,True,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,True,False,False,True,False
8,False,False,False,False,True,False,False,False
9,False,False,False,False,False,False,False,True

In [46]:
df.isna().sum()

customer_id        1
name               1
age                1
email              3
join_date          2
purchase_amount    2
loyalty_member     2
last_purchase      2
dtype: int64

In [47]:
# Dropping missing values
df.dropna() # drop rows with any NA

,customer_id,name,age,email,join_date,purchase_amount,loyalty_member,last_purchase
4,105.0,Eve Wilson,28.0,eve@example.com,2023-01-01,55.75,YES,2023-04-05
6,106.0,Frank White,72.0,frank@example.com,2020-05-12,300.00,no,2023-02-28

In [48]:
df.dropna(how='all') # drop rows where all are NA

,customer_id,name,age,email,join_date,purchase_amount,loyalty_member,last_purchase
0,101.0,Alice Smith,25.0,alice@example.com,None,120.50,None,2023-04-10
1,NaN,Bob Johnson,32.0,bob@example.com,2021-11-03,80.25,No,2023-03-15
2,103.0,Charlie Brown,NaN,None,2023-02-20,200.00,yes,2023-04-01
3,104.0,None,45.0,None,2022-06-18,NaN,no,None
4,105.0,Eve Wilson,28.0,eve@example.com,2023-01-01,55.75,YES,2023-04-05
5,101.0,alice smith,25.0,alice@example.com,2022-01-15,NaN,Yes,2023-04-10
6,106.0,Frank White,72.0,frank@example.com,2020-05-12,300.00,no,2023-02-28
7,107.0,Grace Lee,31.0,None,2022-08-22,90.00,None,2023-03-22
8,108.0,Henry Ford,150.0,henry@example.com,None,25.50,yes,1996-01-15
9,104.0,David King,40.0,david@example.com,2022-06-18,180.00,No,None

In [49]:
df.dropna(axis=1) # drop columns with NA

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [50]:
# Filling missing values
df.fillna(0)

,customer_id,name,age,email,join_date,purchase_amount,loyalty_member,last_purchase
0,101.0,Alice Smith,25.0,alice@example.com,0,120.50,0,2023-04-10
1,0.0,Bob Johnson,32.0,bob@example.com,2021-11-03,80.25,No,2023-03-15
2,103.0,Charlie Brown,0.0,0,2023-02-20,200.00,yes,2023-04-01
3,104.0,0,45.0,0,2022-06-18,0.00,no,0
4,105.0,Eve Wilson,28.0,eve@example.com,2023-01-01,55.75,YES,2023-04-05
5,101.0,alice smith,25.0,alice@example.com,2022-01-15,0.00,Yes,2023-04-10
6,106.0,Frank White,72.0,frank@example.com,2020-05-12,300.00,no,2023-02-28
7,107.0,Grace Lee,31.0,0,2022-08-22,90.00,0,2023-03-22
8,108.0,Henry Ford,150.0,henry@example.com,0,25.50,yes,1996-01-15
9,104.0,David King,40.0,david@example.com,2022-06-18,180.00,No,0

In [51]:
# Fill NaN with column means only for numeric columns
df.fillna(df.select_dtypes(include='number').mean())

,customer_id,name,age,email,join_date,purchase_amount,loyalty_member,last_purchase
0,101.000000,Alice Smith,25.000000,alice@example.com,None,120.50,None,2023-04-10
1,104.333333,Bob Johnson,32.000000,bob@example.com,2021-11-03,80.25,No,2023-03-15
2,103.000000,Charlie Brown,49.777778,None,2023-02-20,200.00,yes,2023-04-01
3,104.000000,None,45.000000,None,2022-06-18,131.50,no,None
4,105.000000,Eve Wilson,28.000000,eve@example.com,2023-01-01,55.75,YES,2023-04-05
5,101.000000,alice smith,25.000000,alice@example.com,2022-01-15,131.50,Yes,2023-04-10
6,106.000000,Frank White,72.000000,frank@example.com,2020-05-12,300.00,no,2023-02-28
7,107.000000,Grace Lee,31.000000,None,2022-08-22,90.00,None,2023-03-22
8,108.000000,Henry Ford,150.000000,henry@example.com,None,25.50,yes,1996-01-15
9,104.000000,David King,40.000000,david@example.com,2022-06-18,180.00,No,None

But if all columns are numeric, you can write like:
- df.fillna(df.mean)

In [52]:
df.fillna(method='ffill') # forward fill

<ipython-input-52-bb9894efdb98>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill') # forward fill

,customer_id,name,age,email,join_date,purchase_amount,loyalty_member,last_purchase
0,101.0,Alice Smith,25.0,alice@example.com,None,120.50,None,2023-04-10
1,101.0,Bob Johnson,32.0,bob@example.com,2021-11-03,80.25,No,2023-03-15
2,103.0,Charlie Brown,32.0,bob@example.com,2023-02-20,200.00,yes,2023-04-01
3,104.0,Charlie Brown,45.0,bob@example.com,2022-06-18,200.00,no,2023-04-01
4,105.0,Eve Wilson,28.0,eve@example.com,2023-01-01,55.75,YES,2023-04-05
5,101.0,alice smith,25.0,alice@example.com,2022-01-15,55.75,Yes,2023-04-10
6,106.0,Frank White,72.0,frank@example.com,2020-05-12,300.00,no,2023-02-28
7,107.0,Grace Lee,31.0,frank@example.com,2022-08-22,90.00,no,2023-03-22
8,108.0,Henry Ford,150.0,henry@example.com,2022-08-22,25.50,yes,1996-01-15
9,104.0,David King,40.0,david@example.com,2022-06-18,180.00,No,1996-01-15

# Removing Dublicates

In [53]:
df.drop_duplicates()

,customer_id,name,age,email,join_date,purchase_amount,loyalty_member,last_purchase
0,101.0,Alice Smith,25.0,alice@example.com,None,120.50,None,2023-04-10
1,NaN,Bob Johnson,32.0,bob@example.com,2021-11-03,80.25,No,2023-03-15
2,103.0,Charlie Brown,NaN,None,2023-02-20,200.00,yes,2023-04-01
3,104.0,None,45.0,None,2022-06-18,NaN,no,None
4,105.0,Eve Wilson,28.0,eve@example.com,2023-01-01,55.75,YES,2023-04-05
5,101.0,alice smith,25.0,alice@example.com,2022-01-15,NaN,Yes,2023-04-10
6,106.0,Frank White,72.0,frank@example.com,2020-05-12,300.00,no,2023-02-28
7,107.0,Grace Lee,31.0,None,2022-08-22,90.00,None,2023-03-22
8,108.0,Henry Ford,150.0,henry@example.com,None,25.50,yes,1996-01-15
9,104.0,David King,40.0,david@example.com,2022-06-18,180.00,No,None

#Data Transformation

In [54]:
# Replacing values
df['age'].replace(np.nan, 0)

0     25.0
1     32.0
2      0.0
3     45.0
4     28.0
5     25.0
6     72.0
7     31.0
8    150.0
9     40.0
Name: age, dtype: float64

In [55]:
df.replace({'age': {0: 'zero', 25: 'quarter'}})

,customer_id,name,age,email,join_date,purchase_amount,loyalty_member,last_purchase
0,101.0,Alice Smith,quarter,alice@example.com,None,120.50,None,2023-04-10
1,NaN,Bob Johnson,32.0,bob@example.com,2021-11-03,80.25,No,2023-03-15
2,103.0,Charlie Brown,NaN,None,2023-02-20,200.00,yes,2023-04-01
3,104.0,None,45.0,None,2022-06-18,NaN,no,None
4,105.0,Eve Wilson,28.0,eve@example.com,2023-01-01,55.75,YES,2023-04-05
5,101.0,alice smith,quarter,alice@example.com,2022-01-15,NaN,Yes,2023-04-10
6,106.0,Frank White,72.0,frank@example.com,2020-05-12,300.00,no,2023-02-28
7,107.0,Grace Lee,31.0,None,2022-08-22,90.00,None,2023-03-22
8,108.0,Henry Ford,150.0,henry@example.com,None,25.50,yes,1996-01-15
9,104.0,David King,40.0,david@example.com,2022-06-18,180.00,No,None

In [56]:
# String operations
df['name'].str.upper()

0      ALICE SMITH
1      BOB JOHNSON
2    CHARLIE BROWN
3             None
4       EVE WILSON
5      ALICE SMITH
6      FRANK WHITE
7        GRACE LEE
8       HENRY FORD
9       DAVID KING
Name: name, dtype: object

In [57]:
df['name'].str.contains('Al')

0     True
1    False
2    False
3     None
4    False
5    False
6    False
7    False
8    False
9    False
Name: name, dtype: object

In [58]:
# Binning continuous data
pd.cut(df['age'], bins=[0, 18, 35, 60, 100],
       labels=['child', 'young', 'adult', 'senior'])

0     young
1     young
2       NaN
3     adult
4     young
5     young
6    senior
7     young
8       NaN
9     adult
Name: age, dtype: category
Categories (4, object): ['child' < 'young' < 'adult' < 'senior']

In [59]:
# One-hot encoding
pd.get_dummies(df['loyalty_member'])

      No    YES    Yes     no    yes
0  False  False  False  False  False
1   True  False  False  False  False
2  False  False  False  False   True
3  False  False  False   True  False
4  False   True  False  False  False
5  False  False   True  False  False
6  False  False  False   True  False
7  False  False  False  False  False
8  False  False  False  False   True
9   True  False  False  False  False

#Practise Exercises:

Create a DataFrame with missing values and practice:

- Identifying missing values

- Dropping rows/columns with missing values

- Filling missing values with different strategies

In [60]:
data = {
    "order_id": [
        1001, 1002, 1003, 1004, 1005, 1001, 1006, 1007, 1008, 1004,
        1009, 1010, 1011, 1012, 1013, 1009, 1014, 1015, 1016, 1017,
        1018, 1019, 1020, 1021, 1022, 1020, 1023, 1024, 1025, 1026,
        1027, 1028, 1029, 1030, 1031, 1027, 1032, 1033, 1034, 1035,
        1036, 1037, 1038, 1039, 1040, 1036, 1041, 1042, 1043, 1044,
        1045, 1046, 1047, 1048, 1049, 1045, 1050, 1051, 1052, 1053,
        1054, 1055, 1056, 1057, 1058, 1054, 1059, 1060, 1061, 1062
    ],
    "customer_name": [
        "alice cooper", "bob marley", "charlie chaplin", None, "EVE ENFORCER", "Alice Cooper",
        "FRANK SINATRA", "grace hopper", "HENRY FORD", "david bowie",
        "ivan drago", "julia roberts", "kate winslet", None, "LEO DICAPRIO", "ivan drago",
        "MORGAN FREEMAN", "NATALIE PORTMAN", "ORLANDO BLOOM", None,
        "PAUL MCCARTNEY", "quentin tarantino", None, "SAMUEL JACKSON", "TOM HANKS", "quentin tarantino",
        "UMA THURMAN", None, "WINONA RYDER", "ZOE SALDANA",
        "BRAD PITT", "jennifer lawrence", "WILL SMITH", "scarlett johansson", "ROBERT DOWNEY", "Brad Pitt",
        "ANGELINA JOLIE", None, "LEONARDO DICAPRIO", "emma stone",
        "RYAN GOSLING", "margot robbie", "CHRIS EVANS", None, "anne hathaway", "Ryan Gosling",
        "MATT DAMON", "charlize theron", "HUGH JACKMAN", "amy adams",
        "DENZEL WASHINGTON", None, "MERYL STREEP", "CATE BLANCHETT", "anthony hopkins", "Denzel Washington",
        "HELEN MIRREN", "GARY OLDMAN", None, "FRANCES MCDORMAND",
        "joaquin phoenix", "TILDA SWINTON", "CHRISTIAN BALE", None, "viola davis", "joaquin phoenix",
        "JULIANNE MOORE", "PHILIP SEYMOUR", "mahershala ali", "LAURA DERN"
    ],
    "email": [
        "alice@example.com", "bob@example.com", "charlie@example.com", "david@example.com", "eve@example.com", "alice@example.com",
        "frank@example.com", None, "henry@example.com", "david@example.com",
        "ivan@example.com", "julia@example.com", None, "leo@example.com", "leo@example.com", "ivan@example.com",
        "morgan@example.com", "natalie@example.com", None, "orlando@example.com",
        "paul@example.com", None, "samuel@example.com", "tom@example.com", "paul@example.com",
        "uma@example.com", "natalie@example.com", "winona@example.com", None,
        "brad@example.com", "jennifer@example.com", "will@example.com", None, "robert@example.com", "brad@example.com",
        "angelina@example.com", "leonardo@example.com", "emma@example.com", "ryan@example.com",
        "margot@example.com", None, "chris@example.com", "anne@example.com", "anne@example.com", "ryan@example.com",
        "matt@example.com", None, "hugh@example.com", "amy@example.com",
        "denzel@example.com", "meryl@example.com", "cate@example.com", "anthony@example.com", "denzel@example.com",
        None, "gary@example.com", "frances@example.com", "joaquin@example.com",
        "tilda@example.com", "christian@example.com", None, "viola@example.com", "joaquin@example.com",
        "julianne@example.com", "philip@example.com", None, "laura@example.com", "john123@example.com",
        "con532ahaha@example.com", "nerdman31@example.com"
    ],
    "purchase_date": [
        "2023-01-15", "2023-02-03", "2023-03-20", "2023-04-18", "2023-05-01", "2023-01-15",
        "2023-06-12", "2023-07-22", "2023-08-30", "2023-04-18",
        "2023-09-05", "2023-10-10", "2023-11-11", "2023-12-01", "2023-12-15", "2023-09-05",
        "2024-01-02", "2024-02-14", "2024-03-03", "2024-04-04",
        "2024-05-05", "2024-06-06", "2024-07-07", "2024-08-08", "2024-09-09", "2024-07-07",
        "2024-10-10", "2024-11-11", "2024-12-12", "2025-01-01",
        "2025-01-15", "2025-01-20", "2025-02-01", "2025-02-14", "2025-02-28", "2025-01-15",
        "2025-03-10", "2025-03-15", "2025-03-20", "2025-03-25",
        "2025-04-01", "2025-04-10", "2025-04-15", "2025-04-20", "2025-04-25", "2025-04-01",
        "2025-05-01", "2025-05-05", "2025-05-10", "2025-05-15",
        "2025-05-20", "2025-05-25", "2025-05-30", "2025-06-01", "2025-06-02", "2025-05-20",
        "2022-12-01", "2022-12-15", "2022-12-20", "2022-12-25",
        "2022-11-01", "2022-11-15", "2022-10-31", "2022-10-15", "2022-09-30", "2022-11-01",
        "2022-09-15", "2022-08-30", "2022-08-15", "2022-07-31"
    ],
    "product": [
        "Laptop", "Phone", "Monitor", "Keyboard", "Mouse", "Laptop",
        "Headphones", "Tablet", "Laptop", "Keyboard",
        "Phone", "Monitor", "Mouse", "Tablet", "Laptop", "Phone",
        "Monitor", "Keyboard", "Mouse", None,
        "Tablet", "Laptop", "Phone", "Monitor", "Keyboard", "Phone",
        "Mouse", "Tablet", "Headphones", "Laptop",
        "Phone", "Monitor", "Headphones", "Tablet", "Mouse", "Phone",
        "Laptop", "Keyboard", "Monitor", "Headphones",
        "Tablet", "Mouse", "Phone", "Laptop", None, "Tablet",
        "Keyboard", "Monitor", "Headphones", "Phone",
        "Laptop", "Mouse", "Tablet", None, "Keyboard", "Laptop",
        "Monitor", "Phone", "Headphones", "Mouse",
        "Tablet", "Laptop", "Keyboard", "Monitor", "Phone", "Tablet",
        None, "Headphones", "Mouse", "Laptop"
    ],
    "price ($)": [
        "$1200.50", "$800.25", "$200.00", "$50.99", "$25.75", "$1200.50",
        "$300.00", "$450.00", "$1300.00", "$50.99",
        "$850.75", "$220.00", "$30.00", "$500.00", "$1250.00", "$850.75",
        "$220.00", "$50.99", "$25.75", "$320.00",
        "$450.00", "$1200.50", "$800.25", None, "$50.99", "$800.25",
        "$25.75", "$450.00", "$300.00", "$1200.50",
        "$799.99", "$210.50", "$280.00", "$520.75", "$35.99", "$799.99",
        "$1150.00", "$45.50", "$195.00", "$295.50",
        "$480.25", "$28.99", "$825.00", "$1175.99", None, "$480.25",
        "$52.75", "$225.00", "$315.50", "$750.00",
        "$1099.99", "$22.50", "$595.00", "$380.75", "$48.25", "$1099.99",
        "$240.00", "$890.50", "$325.00", "$33.75",
        "$650.00", "$1225.75", "$55.99", "$275.50", "$810.25", "$650.00",
        "$405.00", "$340.75", "$29.99", "$1050.00"
    ],
    "payment_method": [
        "CREDIT CARD", "PayPal", "credit card", "CASH", "paypal", "CREDIT CARD",
        "Bitcoin", "CASH", "CREDIT CARD", "CASH",
        "paypal", "Credit Card", "cash", "paypal", "Credit Card", "paypal",
        "Cash", "Credit Card", "CASH", "paypal",
        "Credit Card", None, "Cash", "Paypal", "Credit Card", "Paypal",
        "Cash", "Paypal", "Credit Card", "CASH",
        "credit card", "PAYPAL", "Cash", "Bitcoin", "CREDIT CARD", "credit card",
        "paypal", "CASH", "Credit Card", "paypal",
        "BITCOIN", "cash", "Credit Card", None, "paypal", "BITCOIN",
        "Cash", "credit card", "PAYPAL", "Cash",
        "Credit Card", "bitcoin", None, "CASH", "paypal", "Credit Card",
        "PAYPAL", "cash", "Bitcoin", "credit card",
        "Cash", "CREDIT CARD", "paypal", "Bitcoin", None, "Cash",
        "Credit Card", "PAYPAL", "cash", "bitcoin"
    ]
}


# Convert to DataFrame
df = pd.DataFrame(data)

print("🔥 Welcome to ChaosMart - The Messiest (and Now Bigger) Dataset Alive! 🔥")
print(df)

🔥 Welcome to ChaosMart - The Messiest (and Now Bigger) Dataset Alive! 🔥
    order_id    customer_name                    email purchase_date  \
0       1001     alice cooper        alice@example.com    2023-01-15
1       1002       bob marley          bob@example.com    2023-02-03
2       1003  charlie chaplin      charlie@example.com    2023-03-20
3       1004             None        david@example.com    2023-04-18
4       1005     EVE ENFORCER          eve@example.com    2023-05-01
..       ...              ...                      ...           ...
65      1054  joaquin phoenix                     None    2022-11-01
66      1059   JULIANNE MOORE        laura@example.com    2022-09-15
67      1060   PHILIP SEYMOUR      john123@example.com    2022-08-30
68      1061   mahershala ali  con532ahaha@example.com    2022-08-15
69      1062       LAURA DERN    nerdman31@example.com    2022-07-31

       product price ($) payment_method
0       Laptop  $1200.50    CREDIT CARD
1        Phone   $800.25         PayPal
2      Monitor   $200.00    credit card
3     Keyboard    $50.99           CASH
4        Mouse    $25.75         paypal
..         ...       ...            ...
65      Tablet   $650.00           Cash
66        None   $405.00    Credit Card
67  Headphones   $340.75         PAYPAL
68       Mouse    $29.99           cash
69      Laptop  $1050.00        bitcoin

[70 rows x 7 columns]

In [61]:
for key, value in data.items():
    print(f"{key}: {len(value)}")

order_id: 70
customer_name: 70
email: 70
purchase_date: 70
product: 70
price ($): 70
payment_method: 70

In [62]:
#Drop duplicates, keeping the first occurrence.
df = df.drop_duplicates(subset="order_id", keep="first")
df

,order_id,customer_name,email,purchase_date,product,price ($),payment_method
0,1001,alice cooper,alice@example.com,2023-01-15,Laptop,$1200.50,CREDIT CARD
1,1002,bob marley,bob@example.com,2023-02-03,Phone,$800.25,PayPal
2,1003,charlie chaplin,charlie@example.com,2023-03-20,Monitor,$200.00,credit card
3,1004,None,david@example.com,2023-04-18,Keyboard,$50.99,CASH
4,1005,EVE ENFORCER,eve@example.com,2023-05-01,Mouse,$25.75,paypal
...,...,...,...,...,...,...,...
64,1058,viola davis,philip@example.com,2022-09-30,Phone,$810.25,None
66,1059,JULIANNE MOORE,laura@example.com,2022-09-15,None,$405.00,Credit Card
67,1060,PHILIP SEYMOUR,john123@example.com,2022-08-30,Headphones,$340.75,PAYPAL
68,1061,mahershala ali,con532ahaha@example.com,2022-08-15,Mouse,$29.99,cash
69,1062,LAURA DERN,nerdman31@example.com,2022-07-31,Laptop,$1050.00,bitcoin

In [63]:
# Standardize to Title Case
df["customer_name"] = df["customer_name"].str.title()
df["payment_method"] = df["payment_method"].str.title()

#Fill missing names with "UNKNOWN"
df["customer_name"] = df["customer_name"].fillna("UNKNOWN")

df

,order_id,customer_name,email,purchase_date,product,price ($),payment_method
0,1001,Alice Cooper,alice@example.com,2023-01-15,Laptop,$1200.50,Credit Card
1,1002,Bob Marley,bob@example.com,2023-02-03,Phone,$800.25,Paypal
2,1003,Charlie Chaplin,charlie@example.com,2023-03-20,Monitor,$200.00,Credit Card
3,1004,UNKNOWN,david@example.com,2023-04-18,Keyboard,$50.99,Cash
4,1005,Eve Enforcer,eve@example.com,2023-05-01,Mouse,$25.75,Paypal
...,...,...,...,...,...,...,...
64,1058,Viola Davis,philip@example.com,2022-09-30,Phone,$810.25,None
66,1059,Julianne Moore,laura@example.com,2022-09-15,None,$405.00,Credit Card
67,1060,Philip Seymour,john123@example.com,2022-08-30,Headphones,$340.75,Paypal
68,1061,Mahershala Ali,con532ahaha@example.com,2022-08-15,Mouse,$29.99,Cash
69,1062,Laura Dern,nerdman31@example.com,2022-07-31,Laptop,$1050.00,Bitcoin

In [64]:
df["email"] = df["email"].fillna("no_email@example.com")

# Optional: Mark duplicates (for investigation)
df["is_email_duplicate"] = df["email"].duplicated(keep=False)

df

,order_id,customer_name,email,purchase_date,product,price ($),payment_method,is_email_duplicate
0,1001,Alice Cooper,alice@example.com,2023-01-15,Laptop,$1200.50,Credit Card,False
1,1002,Bob Marley,bob@example.com,2023-02-03,Phone,$800.25,Paypal,False
2,1003,Charlie Chaplin,charlie@example.com,2023-03-20,Monitor,$200.00,Credit Card,False
3,1004,UNKNOWN,david@example.com,2023-04-18,Keyboard,$50.99,Cash,False
4,1005,Eve Enforcer,eve@example.com,2023-05-01,Mouse,$25.75,Paypal,False
...,...,...,...,...,...,...,...,...
64,1058,Viola Davis,philip@example.com,2022-09-30,Phone,$810.25,None,False
66,1059,Julianne Moore,laura@example.com,2022-09-15,None,$405.00,Credit Card,False
67,1060,Philip Seymour,john123@example.com,2022-08-30,Headphones,$340.75,Paypal,False
68,1061,Mahershala Ali,con532ahaha@example.com,2022-08-15,Mouse,$29.99,Cash,False
69,1062,Laura Dern,nerdman31@example.com,2022-07-31,Laptop,$1050.00,Bitcoin,False

In [65]:
# Convert price ($) to float
df["price ($)"] = df["price ($)"].str.replace("$", "").astype(float)

# Cap unrealistic prices at $2000 (assume anything above is an error).
df["price ($)"] = df["price ($)"].clip(upper=2000)  # Cap at $2000
df

,order_id,customer_name,email,purchase_date,product,price ($),payment_method,is_email_duplicate
0,1001,Alice Cooper,alice@example.com,2023-01-15,Laptop,1200.50,Credit Card,False
1,1002,Bob Marley,bob@example.com,2023-02-03,Phone,800.25,Paypal,False
2,1003,Charlie Chaplin,charlie@example.com,2023-03-20,Monitor,200.00,Credit Card,False
3,1004,UNKNOWN,david@example.com,2023-04-18,Keyboard,50.99,Cash,False
4,1005,Eve Enforcer,eve@example.com,2023-05-01,Mouse,25.75,Paypal,False
...,...,...,...,...,...,...,...,...
64,1058,Viola Davis,philip@example.com,2022-09-30,Phone,810.25,None,False
66,1059,Julianne Moore,laura@example.com,2022-09-15,None,405.00,Credit Card,False
67,1060,Philip Seymour,john123@example.com,2022-08-30,Headphones,340.75,Paypal,False
68,1061,Mahershala Ali,con532ahaha@example.com,2022-08-15,Mouse,29.99,Cash,False
69,1062,Laura Dern,nerdman31@example.com,2022-07-31,Laptop,1050.00,Bitcoin,False

In [66]:
# Convert purchase_date to data format
df["purchase_date"] = pd.to_datetime(df["purchase_date"])

df = df[df["purchase_date"].dt.year >= 2000]  # Keep only recent orders

valid_products = ["Laptop", "Phone", "Monitor", "Keyboard", "Mouse", "Headphones", "Tablet"]
df = df[df["product"].isin(valid_products)]

df

,order_id,customer_name,email,purchase_date,product,price ($),payment_method,is_email_duplicate
0,1001,Alice Cooper,alice@example.com,2023-01-15,Laptop,1200.50,Credit Card,False
1,1002,Bob Marley,bob@example.com,2023-02-03,Phone,800.25,Paypal,False
2,1003,Charlie Chaplin,charlie@example.com,2023-03-20,Monitor,200.00,Credit Card,False
3,1004,UNKNOWN,david@example.com,2023-04-18,Keyboard,50.99,Cash,False
4,1005,Eve Enforcer,eve@example.com,2023-05-01,Mouse,25.75,Paypal,False
6,1006,Frank Sinatra,frank@example.com,2023-06-12,Headphones,300.00,Bitcoin,False
7,1007,Grace Hopper,no_email@example.com,2023-07-22,Tablet,450.00,Cash,True
8,1008,Henry Ford,henry@example.com,2023-08-30,Laptop,1300.00,Credit Card,False
10,1009,Ivan Drago,ivan@example.com,2023-09-05,Phone,850.75,Paypal,False
11,1010,Julia Roberts,julia@example.com,2023-10-10,Monitor,220.00,Credit Card,False
12,1011,Kate Winslet,no_email@example.com,2023-11-11,Mouse,30.00,Cash,True
13,1012,UNKNOWN,leo@example.com,2023-12-01,Tablet,500.00,Paypal,True
14,1013,Leo Dicaprio,leo@example.com,2023-12-15,Laptop,1250.00,Credit Card,True
16,1014,Morgan Freeman,morgan@example.com,2024-01-02,Monitor,220.00,Cash,False
17,1015,Natalie Portman,natalie@example.com,2024-02-14,Keyboard,50.99,Credit Card,True
18,1016,Orlando Bloom,no_email@example.com,2024-03-03,Mouse,25.75,Cash,True
20,1018,Paul Mccartney,paul@example.com,2024-05-05,Tablet,450.00,Credit Card,True
21,1019,Quentin Tarantino,no_email@example.com,2024-06-06,Laptop,1200.50,None,True
22,1020,UNKNOWN,samuel@example.com,2024-07-07,Phone,800.25,Cash,False
23,1021,Samuel Jackson,tom@example.com,2024-08-08,Monitor,NaN,Paypal,False
24,1022,Tom Hanks,paul@example.com,2024-09-09,Keyboard,50.99,Credit Card,True
26,1023,Uma Thurman,natalie@example.com,2024-10-10,Mouse,25.75,Cash,True
27,1024,UNKNOWN,winona@example.com,2024-11-11,Tablet,450.00,Paypal,False
28,1025,Winona Ryder,no_email@example.com,2024-12-12,Headphones,300.00,Credit Card,True
29,1026,Zoe Saldana,brad@example.com,2025-01-01,Laptop,1200.50,Cash,True
30,1027,Brad Pitt,jennifer@example.com,2025-01-15,Phone,799.99,Credit Card,False
31,1028,Jennifer Lawrence,will@example.com,2025-01-20,Monitor,210.50,Paypal,False
32,1029,Will Smith,no_email@example.com,2025-02-01,Headphones,280.00,Cash,True
33,1030,Scarlett Johansson,robert@example.com,2025-02-14,Tablet,520.75,Bitcoin,False
34,1031,Robert Downey,brad@example.com,2025-02-28,Mouse,35.99,Credit Card,True
36,1032,Angelina Jolie,leonardo@example.com,2025-03-10,Laptop,1150.00,Paypal,False
37,1033,UNKNOWN,emma@example.com,2025-03-15,Keyboard,45.50,Cash,False
38,1034,Leonardo Dicaprio,ryan@example.com,2025-03-20,Monitor,195.00,Credit Card,True
39,1035,Emma Stone,margot@example.com,2025-03-25,Headphones,295.50,Paypal,False
40,1036,Ryan Gosling,no_email@example.com,2025-04-01,Tablet,480.25,Bitcoin,True
41,1037,Margot Robbie,chris@example.com,2025-04-10,Mouse,28.99,Cash,False
42,1038,Chris Evans,anne@example.com,2025-04-15,Phone,825.00,Credit Card,True
43,1039,UNKNOWN,anne@example.com,2025-04-20,Laptop,1175.99,None,True
46,1041,Matt Damon,no_email@example.com,2025-05-01,Keyboard,52.75,Cash,True
47,1042,Charlize Theron,hugh@example.com,2025-05-05,Monitor,225.00,Credit Card,False
48,1043,Hugh Jackman,amy@example.com,2025-05-10,Headphones,315.50,Paypal,False
49,1044,Amy Adams,denzel@example.com,2025-05-15,Phone,750.00,Cash,True
50,1045,Denzel Washington,meryl@example.com,2025-05-20,Laptop,1099.99,Credit Card,False
51,1046,UNKNOWN,cate@example.com,2025-05-25,Mouse,22.50,Bitcoin,False
52,1047,Meryl Streep,anthony@example.com,2025-05-30,Tablet,595.00,None,False
54,1049,Anthony Hopkins,no_email@example.com,2025-06-02,Keyboard,48.25,Paypal,True
56,1050,Helen Mirren,frances@example.com,2022-12-01,Monitor,240.00,Paypal,False
57,1051,Gary Oldman,joaquin@example.com,2022-12-15,Phone,890.50,Cash,True
58,1052,UNKNOWN,tilda@example.com,2022-12-20,Headphones,325.00,Bitcoin,False
59,1053,Frances Mcdormand,christian@example.com,2022-12-25,Mouse,33.75,Credit Card,False
60,1054,Joaquin Phoenix,no_email@example.com,2022-11-01,Tablet,650.00,Cash,True
61,1055,Tilda Swinton,viola@example.com,2022-11-15,Laptop,1225.75,Credit Card,False
62,1056,Christian Bale,joaquin@example.com,2022-10-31,Keyboard,55.99,Paypal,True
63,1057,UNKNOWN,julianne@example.com,2022-10-15,Monitor,275.50,Bitcoin,False
64,1058,Viola Davis,philip@example.com,2022-09-30,Phone,810.25,None,False
67,1060,Philip Seymour,john123@example.com,2022-08-30,Headphones,340.75,Paypal,False
68,1061,Mahershala Ali,con532ahaha@example.com,2022-08-15,Mouse,29.99,Cash,False
69,1062,Laura Dern,nerdman31@example.com,2022-07-31,Laptop,1050.00,Bitcoin,False

#GroupBy Fundamentals

The groupby operation splits data into groups, applies a function to each group, and combines the results.

In [67]:
# Basic grouping
grouped = df.groupby('product')
grouped

In [68]:
# Group the DataFrame by 'product' and 'order_id'
grouped = df.groupby(['product', 'order_id'])
grouped

In [69]:
for group_name, group_data in grouped:
    print("="*80)  # Add a separator line for better readability
    print(f"Group: Product={group_name[0]}, Order ID={group_name[1]}")
    print(group_data.reset_index(drop=False).head())
    print("="*80 + "\n")  # Another separator and a newline for spacing

================================================================================
Group: Product=Headphones, Order ID=1006
   index  order_id  customer_name              email purchase_date  \
0      6      1006  Frank Sinatra  frank@example.com    2023-06-12

      product  price ($) payment_method  is_email_duplicate
0  Headphones      300.0        Bitcoin               False
================================================================================

================================================================================
Group: Product=Headphones, Order ID=1025
   index  order_id customer_name                 email purchase_date  \
0     28      1025  Winona Ryder  no_email@example.com    2024-12-12

      product  price ($) payment_method  is_email_duplicate
0  Headphones      300.0    Credit Card                True
================================================================================

================================================================================
Group: Product=Headphones, Order ID=1029
   index  order_id customer_name                 email purchase_date  \
0     32      1029    Will Smith  no_email@example.com    2025-02-01

      product  price ($) payment_method  is_email_duplicate
0  Headphones      280.0           Cash                True
================================================================================

================================================================================
Group: Product=Headphones, Order ID=1035
   index  order_id customer_name               email purchase_date  \
0     39      1035    Emma Stone  margot@example.com    2025-03-25

      product  price ($) payment_method  is_email_duplicate
0  Headphones      295.5         Paypal               False
================================================================================

================================================================================
Group: Product=Headphones, Order ID=1043
   index  order_id customer_name            email purchase_date     product  \
0     48      1043  Hugh Jackman  amy@example.com    2025-05-10  Headphones

   price ($) payment_method  is_email_duplicate
0      315.5         Paypal               False
================================================================================

================================================================================
Group: Product=Headphones, Order ID=1052
   index  order_id customer_name              email purchase_date     product  \
0     58      1052       UNKNOWN  tilda@example.com    2022-12-20  Headphones

   price ($) payment_method  is_email_duplicate
0      325.0        Bitcoin               False
================================================================================

================================================================================
Group: Product=Headphones, Order ID=1060
   index  order_id   customer_name                email purchase_date  \
0     67      1060  Philip Seymour  john123@example.com    2022-08-30

      product  price ($) payment_method  is_email_duplicate
0  Headphones     340.75         Paypal               False
================================================================================

================================================================================
Group: Product=Keyboard, Order ID=1004
   index  order_id customer_name              email purchase_date   product  \
0      3      1004       UNKNOWN  david@example.com    2023-04-18  Keyboard

   price ($) payment_method  is_email_duplicate
0      50.99           Cash               False
================================================================================

================================================================================
Group: Product=Keyboard, Order ID=1015
   index  order_id    customer_name                email purchase_date  \
0     17      1015  Natalie Portman  natalie@example.com    2024-02-14

    product  price ($) payment_method  is_email_duplicate
0  Keyboard      50.99    Credit Card                True
================================================================================

================================================================================
Group: Product=Keyboard, Order ID=1022
   index  order_id customer_name             email purchase_date   product  \
0     24      1022     Tom Hanks  paul@example.com    2024-09-09  Keyboard

   price ($) payment_method  is_email_duplicate
0      50.99    Credit Card                True
================================================================================

================================================================================
Group: Product=Keyboard, Order ID=1033
   index  order_id customer_name             email purchase_date   product  \
0     37      1033       UNKNOWN  emma@example.com    2025-03-15  Keyboard

   price ($) payment_method  is_email_duplicate
0       45.5           Cash               False
================================================================================

================================================================================
Group: Product=Keyboard, Order ID=1041
   index  order_id customer_name                 email purchase_date  \
0     46      1041    Matt Damon  no_email@example.com    2025-05-01

    product  price ($) payment_method  is_email_duplicate
0  Keyboard      52.75           Cash                True
================================================================================

================================================================================
Group: Product=Keyboard, Order ID=1049
   index  order_id    customer_name                 email purchase_date  \
0     54      1049  Anthony Hopkins  no_email@example.com    2025-06-02

    product  price ($) payment_method  is_email_duplicate
0  Keyboard      48.25         Paypal                True
================================================================================

================================================================================
Group: Product=Keyboard, Order ID=1056
   index  order_id   customer_name                email purchase_date  \
0     62      1056  Christian Bale  joaquin@example.com    2022-10-31

    product  price ($) payment_method  is_email_duplicate
0  Keyboard      55.99         Paypal                True
================================================================================

================================================================================
Group: Product=Laptop, Order ID=1001
   index  order_id customer_name              email purchase_date product  \
0      0      1001  Alice Cooper  alice@example.com    2023-01-15  Laptop

   price ($) payment_method  is_email_duplicate
0     1200.5    Credit Card               False
================================================================================

================================================================================
Group: Product=Laptop, Order ID=1008
   index  order_id customer_name              email purchase_date product  \
0      8      1008    Henry Ford  henry@example.com    2023-08-30  Laptop

   price ($) payment_method  is_email_duplicate
0     1300.0    Credit Card               False
================================================================================

================================================================================
Group: Product=Laptop, Order ID=1013
   index  order_id customer_name            email purchase_date product  \
0     14      1013  Leo Dicaprio  leo@example.com    2023-12-15  Laptop

   price ($) payment_method  is_email_duplicate
0     1250.0    Credit Card                True
================================================================================

================================================================================
Group: Product=Laptop, Order ID=1019
   index  order_id      customer_name                 email purchase_date  \
0     21      1019  Quentin Tarantino  no_email@example.com    2024-06-06

  product  price ($) payment_method  is_email_duplicate
0  Laptop     1200.5           None                True
================================================================================

================================================================================
Group: Product=Laptop, Order ID=1026
   index  order_id customer_name             email purchase_date product  \
0     29      1026   Zoe Saldana  brad@example.com    2025-01-01  Laptop

   price ($) payment_method  is_email_duplicate
0     1200.5           Cash                True
================================================================================

================================================================================
Group: Product=Laptop, Order ID=1032
   index  order_id   customer_name                 email purchase_date  \
0     36      1032  Angelina Jolie  leonardo@example.com    2025-03-10

  product  price ($) payment_method  is_email_duplicate
0  Laptop     1150.0         Paypal               False
================================================================================

================================================================================
Group: Product=Laptop, Order ID=1039
   index  order_id customer_name             email purchase_date product  \
0     43      1039       UNKNOWN  anne@example.com    2025-04-20  Laptop

   price ($) payment_method  is_email_duplicate
0    1175.99           None                True
================================================================================

================================================================================
Group: Product=Laptop, Order ID=1045
   index  order_id      customer_name              email purchase_date  \
0     50      1045  Denzel Washington  meryl@example.com    2025-05-20

  product  price ($) payment_method  is_email_duplicate
0  Laptop    1099.99    Credit Card               False
================================================================================

================================================================================
Group: Product=Laptop, Order ID=1055
   index  order_id  customer_name              email purchase_date product  \
0     61      1055  Tilda Swinton  viola@example.com    2022-11-15  Laptop

   price ($) payment_method  is_email_duplicate
0    1225.75    Credit Card               False
================================================================================

================================================================================
Group: Product=Laptop, Order ID=1062
   index  order_id customer_name                  email purchase_date product  \
0     69      1062    Laura Dern  nerdman31@example.com    2022-07-31  Laptop

   price ($) payment_method  is_email_duplicate
0     1050.0        Bitcoin               False
================================================================================

================================================================================
Group: Product=Monitor, Order ID=1003
   index  order_id    customer_name                email purchase_date  \
0      2      1003  Charlie Chaplin  charlie@example.com    2023-03-20

   product  price ($) payment_method  is_email_duplicate
0  Monitor      200.0    Credit Card               False
================================================================================

================================================================================
Group: Product=Monitor, Order ID=1010
   index  order_id  customer_name              email purchase_date  product  \
0     11      1010  Julia Roberts  julia@example.com    2023-10-10  Monitor

   price ($) payment_method  is_email_duplicate
0      220.0    Credit Card               False
================================================================================

================================================================================
Group: Product=Monitor, Order ID=1014
   index  order_id   customer_name               email purchase_date  product  \
0     16      1014  Morgan Freeman  morgan@example.com    2024-01-02  Monitor

   price ($) payment_method  is_email_duplicate
0      220.0           Cash               False
================================================================================

================================================================================
Group: Product=Monitor, Order ID=1021
   index  order_id   customer_name            email purchase_date  product  \
0     23      1021  Samuel Jackson  tom@example.com    2024-08-08  Monitor

   price ($) payment_method  is_email_duplicate
0        NaN         Paypal               False
================================================================================

================================================================================
Group: Product=Monitor, Order ID=1028
   index  order_id      customer_name             email purchase_date  \
0     31      1028  Jennifer Lawrence  will@example.com    2025-01-20

   product  price ($) payment_method  is_email_duplicate
0  Monitor      210.5         Paypal               False
================================================================================

================================================================================
Group: Product=Monitor, Order ID=1034
   index  order_id      customer_name             email purchase_date  \
0     38      1034  Leonardo Dicaprio  ryan@example.com    2025-03-20

   product  price ($) payment_method  is_email_duplicate
0  Monitor      195.0    Credit Card                True
================================================================================

================================================================================
Group: Product=Monitor, Order ID=1042
   index  order_id    customer_name             email purchase_date  product  \
0     47      1042  Charlize Theron  hugh@example.com    2025-05-05  Monitor

   price ($) payment_method  is_email_duplicate
0      225.0    Credit Card               False
================================================================================

================================================================================
Group: Product=Monitor, Order ID=1050
   index  order_id customer_name                email purchase_date  product  \
0     56      1050  Helen Mirren  frances@example.com    2022-12-01  Monitor

   price ($) payment_method  is_email_duplicate
0      240.0         Paypal               False
================================================================================

================================================================================
Group: Product=Monitor, Order ID=1057
   index  order_id customer_name                 email purchase_date  product  \
0     63      1057       UNKNOWN  julianne@example.com    2022-10-15  Monitor

   price ($) payment_method  is_email_duplicate
0      275.5        Bitcoin               False
================================================================================

================================================================================
Group: Product=Mouse, Order ID=1005
   index  order_id customer_name            email purchase_date product  \
0      4      1005  Eve Enforcer  eve@example.com    2023-05-01   Mouse

   price ($) payment_method  is_email_duplicate
0      25.75         Paypal               False
================================================================================

================================================================================
Group: Product=Mouse, Order ID=1011
   index  order_id customer_name                 email purchase_date product  \
0     12      1011  Kate Winslet  no_email@example.com    2023-11-11   Mouse

   price ($) payment_method  is_email_duplicate
0       30.0           Cash                True
================================================================================

================================================================================
Group: Product=Mouse, Order ID=1016
   index  order_id  customer_name                 email purchase_date product  \
0     18      1016  Orlando Bloom  no_email@example.com    2024-03-03   Mouse

   price ($) payment_method  is_email_duplicate
0      25.75           Cash                True
================================================================================

================================================================================
Group: Product=Mouse, Order ID=1023
   index  order_id customer_name                email purchase_date product  \
0     26      1023   Uma Thurman  natalie@example.com    2024-10-10   Mouse

   price ($) payment_method  is_email_duplicate
0      25.75           Cash                True
================================================================================

================================================================================
Group: Product=Mouse, Order ID=1031
   index  order_id  customer_name             email purchase_date product  \
0     34      1031  Robert Downey  brad@example.com    2025-02-28   Mouse

   price ($) payment_method  is_email_duplicate
0      35.99    Credit Card                True
================================================================================

================================================================================
Group: Product=Mouse, Order ID=1037
   index  order_id  customer_name              email purchase_date product  \
0     41      1037  Margot Robbie  chris@example.com    2025-04-10   Mouse

   price ($) payment_method  is_email_duplicate
0      28.99           Cash               False
================================================================================

================================================================================
Group: Product=Mouse, Order ID=1046
   index  order_id customer_name             email purchase_date product  \
0     51      1046       UNKNOWN  cate@example.com    2025-05-25   Mouse

   price ($) payment_method  is_email_duplicate
0       22.5        Bitcoin               False
================================================================================

================================================================================
Group: Product=Mouse, Order ID=1053
   index  order_id      customer_name                  email purchase_date  \
0     59      1053  Frances Mcdormand  christian@example.com    2022-12-25

  product  price ($) payment_method  is_email_duplicate
0   Mouse      33.75    Credit Card               False
================================================================================

================================================================================
Group: Product=Mouse, Order ID=1061
   index  order_id   customer_name                    email purchase_date  \
0     68      1061  Mahershala Ali  con532ahaha@example.com    2022-08-15

  product  price ($) payment_method  is_email_duplicate
0   Mouse      29.99           Cash               False
================================================================================

================================================================================
Group: Product=Phone, Order ID=1002
   index  order_id customer_name            email purchase_date product  \
0      1      1002    Bob Marley  bob@example.com    2023-02-03   Phone

   price ($) payment_method  is_email_duplicate
0     800.25         Paypal               False
================================================================================

================================================================================
Group: Product=Phone, Order ID=1009
   index  order_id customer_name             email purchase_date product  \
0     10      1009    Ivan Drago  ivan@example.com    2023-09-05   Phone

   price ($) payment_method  is_email_duplicate
0     850.75         Paypal               False

# Common Groupby Aggregations

In [70]:
df.groupby('product')['price ($)'].mean().round(2)

product
Headphones     308.11
Keyboard        50.78
Laptop        1185.32
Monitor        223.25
Mouse           28.72
Phone          815.87
Tablet         512.00
Name: price ($), dtype: float64

In [71]:
df.groupby('product')['price ($)'].sum()

product
Headphones     2156.75
Keyboard        355.46
Laptop        11853.23
Monitor        1786.00
Mouse           258.47
Phone          6526.99
Tablet         4096.00
Name: price ($), dtype: float64

In [72]:
df.groupby('product')['price ($)'].agg(['mean', 'sum', 'count', 'std'])

                   mean       sum  count        std
product
Headphones   308.107143   2156.75      7  20.355106
Keyboard      50.780000    355.46      7   3.302438
Laptop      1185.323000  11853.23     10  71.947627
Monitor      223.250000   1786.00      8  25.455844
Mouse         28.718889    258.47      9   4.281196
Phone        815.873750   6526.99      8  41.369748
Tablet       512.000000   4096.00      8  74.348239

#Merging, Joining, and Concatenating

In [73]:
# Customer data (from CRM)
customers = pd.DataFrame({
    'customer_id': [101, 102, 103, 104, 105],
    'name': ['Alice Smith', 'Bob Johnson', 'Charlie Brown', 'Diana Prince', 'Ethan Hunt'],
    'join_date': ['2022-01-15', '2021-11-03', '2023-02-20', '2022-05-10', '2021-07-28'],
    'tier': ['Gold', 'Silver', 'Bronze', 'Gold', 'Silver'],
    'email': ['alice@example.com', 'bob@example.com', 'charlie@example.com',
              'diana@example.com', 'ethan@example.com']
})

# Order data (from transactions)
orders = pd.DataFrame({
    'order_id': [1001, 1002, 1003, 1004, 1005, 1006, 1007],
    'customer_id': [101, 102, 101, 104, 103, 105, 102],
    'order_date': ['2023-05-10', '2023-05-12', '2023-05-15', '2023-05-15',
                   '2023-05-18', '2023-05-20', '2023-05-25'],
    'product_id': ['P100', 'P102', 'P101', 'P100', 'P103', 'P102', 'P104'],
    'quantity': [2, 1, 1, 3, 2, 1, 1],
    'unit_price': [49.99, 89.99, 29.99, 49.99, 19.99, 89.99, 149.99]
})

# Product catalog (from inventory)
products = pd.DataFrame({
    'product_id': ['P100', 'P101', 'P102', 'P103', 'P104'],
    'product_name': ['Wireless Headphones', 'Bluetooth Speaker', 'Smart Watch',
                     'USB-C Cable', 'Tablet Stand'],
    'category': ['Electronics', 'Electronics', 'Wearables', 'Accessories', 'Accessories'],
    'weight_grams': [250, 600, 50, 30, 350]
})

Data Cleaning

In [74]:
# Convert dates to datetime
customers['join_date'] = pd.to_datetime(customers['join_date'])
orders['order_date'] = pd.to_datetime(orders['order_date'])

# Calculate order total
orders['order_total'] = orders['quantity'] * orders['unit_price']

- Merging Operations

In [75]:
# Left join to keep all orders even if customer info is missing
order_customer = pd.merge(orders, customers, on='customer_id', how='left')

print(order_customer.head())

   order_id  customer_id order_date product_id  quantity  unit_price  \
0      1001          101 2023-05-10       P100         2       49.99
1      1002          102 2023-05-12       P102         1       89.99
2      1003          101 2023-05-15       P101         1       29.99
3      1004          104 2023-05-15       P100         3       49.99
4      1005          103 2023-05-18       P103         2       19.99

   order_total           name  join_date    tier                email
0        99.98    Alice Smith 2022-01-15    Gold    alice@example.com
1        89.99    Bob Johnson 2021-11-03  Silver      bob@example.com
2        29.99    Alice Smith 2022-01-15    Gold    alice@example.com
3       149.97   Diana Prince 2022-05-10    Gold    diana@example.com
4        39.98  Charlie Brown 2023-02-20  Bronze  charlie@example.com

In [76]:
# First merge orders with products
order_products = pd.merge(orders, products, on='product_id', how='left')

# Then merge with customer data
complete_orders = pd.merge(order_products, customers, on='customer_id', how='left')

# Reorder columns for better readability
complete_orders = complete_orders[[
    'order_id', 'order_date', 'customer_id', 'name', 'tier',
    'product_id', 'product_name', 'category',
    'quantity', 'unit_price', 'weight_grams'
]]

complete_orders

,order_id,order_date,customer_id,name,tier,product_id,product_name,category,quantity,unit_price,weight_grams
0,1001,2023-05-10,101,Alice Smith,Gold,P100,Wireless Headphones,Electronics,2,49.99,250
1,1002,2023-05-12,102,Bob Johnson,Silver,P102,Smart Watch,Wearables,1,89.99,50
2,1003,2023-05-15,101,Alice Smith,Gold,P101,Bluetooth Speaker,Electronics,1,29.99,600
3,1004,2023-05-15,104,Diana Prince,Gold,P100,Wireless Headphones,Electronics,3,49.99,250
4,1005,2023-05-18,103,Charlie Brown,Bronze,P103,USB-C Cable,Accessories,2,19.99,30
5,1006,2023-05-20,105,Ethan Hunt,Silver,P102,Smart Watch,Wearables,1,89.99,50
6,1007,2023-05-25,102,Bob Johnson,Silver,P104,Tablet Stand,Accessories,1,149.99,350